### ISSUE TITLE
Da sistemare quando mi sloggo da tutti gli account blocca l'interfaccia

### ISSUE THREAD

**Issue by tasuboyz** [davvoz/cur8-steem-telegram#7]
![image](https://github.com/user-attachments/assets/a1062c4e-d476-4474-a4a5-525986febd36)

**Comment by tasuboyz** [comment]
![image](https://github.com/user-attachments/assets/8856f84a-be7f-4767-b4e9-a27490d33194)

**Comment by davvoz** [comment]
fixato qua [](https://github.com/davvoz/cur8-steem-telegram/commit/08e5f95a694ad9933adf8740145dbc2d09799e66)

**Comment by davvoz** [comment]
fixato [qua](https://github.com/davvoz/cur8-steem-telegram/commit/08e5f95a694ad9933adf8740145dbc2d09799e66)

**Comment by davvoz** [comment]
fixed
