### ISSUE TITLE
Failed Load Draft

### ISSUE THREAD

**Issue by tasuboyz** [davvoz/cur8-steem-telegram#8]
![image](https://cdn.steemitimages.com/DQmWQG1Qkn1Q5rU6RSHiWM8hur4EzHTydhB8X8gR7drixwR/image.jpg)

Ogni tanto lo fa

**Comment by davvoz** [comment]
TODO :inibire bottoni di navigazione dopo il logout di tutti gli account

**Comment by tasuboyz** [comment]
https://github.com/davvoz/cur8-steem-telegram/commit/37168cf0e22206a40102e047c9d3354138e6e93d
